### ISSUE TITLE
A callback was made on a garbage collected delegate `CustomModule+ForwardFunctionC`

### ISSUE THREAD

**Issue by lostmsu** [xamarin/TorchSharp#321]
Process terminated. A callback was made on a garbage collected delegate of type `TorchSharp!TorchSharp.torch+nn+CustomModule+ForwardFunctionC::Invoke`.

This happens, because one does not generally has a live reference to an instance of `CustomModule`. For example, when it is part of `Sequential`.

Because the class instance has to be preserved, it needs to allocate a `GCHandle`, that C++ side of the code must hold on to until torch has no more references to the module.

**Comment by NiklasGustafsson** [comment]
@lostmsu -- thanks for reporting. 

If you come up with a small repro case, please let me know.

**Comment by NiklasGustafsson** [comment]
@lostmsu -- I believe a fix to this bug is for the .NET Sequential implementation to hold on to the submodules list that it is given, rather than just handing the native handles to LibTorch.

**Comment by lostmsu** [comment]
@NiklasGustafsson I believe this does the trick:

```csharp
class TestModule : CustomModule {
    public TestModule() : base(nameof(TestModule)) {}

    public override torch.Tensor forward(torch.Tensor t) => t;

    static void Main() {
        var seq = Make();
        GC.Collect();
        GC.WaitForPendingFinalizers();
        GC.Collect();
        seq.forward(torch.zeros(10));
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static Module Make() => Sequential(("t", new TestModule()), ("d", Linear(10, 1)));
}
```

Though this just generates `System.ExecutionEngineException`. So might be an entirely separate issue :-D

**Comment by lostmsu** [comment]
@NiklasGustafsson I think trying to fix `Sequential` is going to be error prone: if there are more composite modules in the future, their developers won't know about the need to keep module instances alive in .NET heap.

`GCHandle` is the correct solution here.

**Comment by NiklasGustafsson** [comment]
Ok. I'll take a look at this tomorrow.

**Comment by NiklasGustafsson** [comment]
@lostmsu -- the repro allowed me to successfully reproduce the bug. Thank you, that made my life much easier. I have incorporated the code into the unit tests.

I see the ExecutionEngineException, but I'm convinced that it's the same problem, since the root cause is that the .NET module reference is GC'd while the native handle still lives on and gets used. The delegate is also GC'd, like you say in the issue title, since the only reference to it is in the module instance. 

Preserving the module references in the Sequential instance addresses the problem and is useful for other purposes, such as the implementation of apply() on the Sequential class.

**Comment by lostmsu** [comment]
@NiklasGustafsson has this fix been released yet?

**Comment by NiklasGustafsson** [comment]
Not yet. 

We're in the middle of moving the repo from Xamarin to .NET Foundation, and haven't made a release recently since we're pre-occupied with that.
