### ISSUE TITLE
Revamp folder structure

### ISSUE THREAD

**Issue by NiklasGustafsson** [xamarin/TorchSharp#34]
We should have a traditional src/test/docs structure.

**Comment by interesaaat** [comment]
Plus namespace names. Should / can we have Microsoft.ML as in ML.NET?

**Comment by markusweimer** [comment]
> Plus namespace names. Should / can we have Microsoft.ML as in ML.NET?

I don't think that is a good idea. Success to me for this project would be acceptance into the PyTorch code base. Maybe we can use `Torch` as the prefix?

**Comment by migueldeicaza** [comment]
Few topics:

Agreed, we do not want "Microsoft" on the prefix.   Makes sense to use "Torch" instead of "TorchSharp", let us do that.

As for the layout of the project, you probably mean the "corefx" lineage, which is only traditional as "in the last couple of years", the tradition of cross platform .NET goes some 17 years back and that is a mixed bag.

I do not mind creating a toplevel for "test" and adding or moving various tests there, the rest I would keep as is.

In particular, "docs" is harder, given that I am publishing the API documentation from GitHub, the formatted docs have to go there, while the source documentation has to go elsewhere.

**Comment by interesaaat** [comment]
I think that all docs related can stay as they are. However it is probably better to factor source code into their proper folders: all tests into the test dir, and the remaining code into src. I also suggest to rename Tester to Sample. 

So the final structure I have in mind is
/docs
/docfx
/ecmadocs
/test
/src
/src/TorchSharp
/src/Sample
(/src/TorchTensor) -> this is the mapping to SNT

For the namespace, I think we should have Torch as root. So TorchSharp will become Torch.TorchSharp (or Torch.Sharp?), and the bindings to SNL as Torch.Sharp.Tensor (I am open to suggestions here).

WDYT?

**Comment by motus** [comment]
@interesaaat looks good - although we have to double check the location of `test/` folder - it can be e.g. under `/src/`. Also, do we plan to keep using `Microsoft.VisualStudio.TestTools.UnitTesting` or switch to, say, `XUnit` or soething?

**Comment by interesaaat** [comment]
`test` should be its own folder IMO.  `UnitTesting` is ok since we already started with that.

**Comment by interesaaat** [comment]
@NiklasGustafsson any specific reason for having the test project not being part of the solution?
