### ISSUE TITLE
Pytorch ver. 1.0 and the C++ Frontend

### ISSUE THREAD

**Issue by artem-hryb** [xamarin/TorchSharp#75]
I am not sure that it is correct place to ask but Pytorch version 1.0 has the C++ Frontend [Pytorch](https://pytorch.org/cppdocs/frontend.html) (that allows consuming all variety of neural network modules, optimization algorithms etc. in c++) . Is there easy way to automate c#<->c++ binding to it?

Basically what I am trying achieve is to use high level api of pytorch in C# like
torch::nll_loss torch::log_softmax or torch::nn::Linear etc.

**Comment by interesaaat** [comment]
Hi @artem-hryb, please look [here](https://github.com/interesaaat/TorchSharp/blob/LibTorchSharpFirstTest/Examples/MNIST.cs). I will try to submit a PR soon-ish so that you can start playing with it from the main TorchSharp repo. For the moment I am trying to port the API manually so that I can understand if there is any specific blocker. After that we will look on how to automate the process (suggestions are welcome if you already have some idea on how to achieve this!)

**Comment by interesaaat** [comment]
Fixed in PR #80
