### ISSUE TITLE
Review of the C# API

### ISSUE THREAD

**Issue by interesaaat** [xamarin/TorchSharp#95]
The C# API now mostly follow libTorch design. I think we need to check if this match C# users expectations.

**Comment by joemoorhouse** [comment]
Seems like a good move to me to follow libTorch design. I find the C++ API nice and intuitive if converting from Python. Personally I think works well in C# (single TorchTensor <=> at::Tensor as opposed to typed varieties). The '_' for 'in place' in Python/libTorch is even growing on me - or is that a bit too un-C#? :)

**Comment by interesaaat** [comment]
Yea I think we need to discuss on this. I don't think we want to make the C# api snake case, unless we want an API more close to Python (#76 )

**Comment by joemoorhouse** [comment]
Would agree with no snake case. I suppose the trailing underscore instead of 'InPlace' is rather snake-casey!

**Comment by Oceania2018** [comment]
Personally, I hope that the naming rules remain the same as PyTorch, reducing the memory burden of developers switching.

**Comment by GeorgeS2019** [comment]
@dsyme

The current naming rules make porting from libtorch c++ to TorchSharp c# more intuitive. 

[Future work on examples](https://github.com/xamarin/TorchSharp/issues/91) 
ResNet for TorchSharp
- instead of refering to a [pytorch example](https://github.com/kuangliu/pytorch-cifar/blob/master/models/resnet.py), perhaps a[ libTorch example ](https://github.com/Keson96/ResNet_LibTorch/blob/master/resnet/resnet.cpp)will be more appropriate for porting.

@Oceania2018 

HaiPing suggestion will make TorchSharp more consistent when porting from PyTorch codes

Perhaps **TorchSharp** stays for porting from libTorch c++
while future version of **Torch.NET** may evolve into a naming rules that make porting from PyTorch (python) to .NET (c#) more intuitive

**Comment by dsyme** [comment]
Covered by https://github.com/xamarin/TorchSharp/pull/205
